### ISSUE TITLE
使用 GitHub.io 代替 Wiki

### ISSUE THREAD

**Issue by StephDC** [TieBaMma/InstallTutorial#1]
建立 gh-pages branch 然後將文檔加進去，之後可以使用 https://tiebamma.github.io/InstallTutorial 訪問。這樣同時允許大家直接修改並提 Pull request

或者使用自動建立腳本（Settings->GitHub Pages->Automatic Page Generator）建立，即可直接把現有內容直接複製進去啦～

**Comment by TieBaMma** [comment]
我也是第一次用Github……是现在这样就行了吗？

**Comment by StephDC** [comment]
看起來不錯，這樣以後大家如果想改就可以直接去開 Pull Request 了
