### ISSUE TITLE
新链接 (SharePoint-API 及备线) 似乎无法打开

### ISSUE THREAD

**Issue by bryango** [TieBaMma/InstallTutorial#105]
https://github.com/TieBaMma/InstallTutorial/commit/08e39b12fff12a8755b4e8dc16b268df2137762e 引入的新链接似乎无法打开。网页跳转至 https://wdm-kb.itsu.eu.org/, Firefox 提示：

> **The page isn’t redirecting properly**
> An error occurred during a connection to wdm-kb.itsu.eu.org.
> This problem can sometimes be caused by disabling or refusing to accept cookies.

Chrome 提示：

> **This page isn’t working**
> wdm-kb.itsu.eu.org redirected you too many times.
> Try clearing your cookies.
> ERR_TOO_MANY_REDIRECTS

而旧链接：https://wdm-v2.itsu.eu.org/share/ 依然可以正常使用。不知是不是本人的网络问题。

**Comment by ryakuia** [comment]
正在与维护者取得联系，这边会推一个修改先把链接改到 wdm-v2 临时用一下。

感谢反馈

**Comment by ryakuia** [comment]
那边说修好了，如果还有访问问题请再打开这个issue，谢谢

**Comment by bryango** [comment]
现在一切正常，感谢！
