### ISSUE TITLE
没有介绍SystemModeler和gridMathematica的相关内容？

### ISSUE THREAD

**Issue by CNMan** [TieBaMma/InstallTutorial#107]
仿真建模：https://zh.wikipedia.org/zh-cn/Wolfram_SystemModeler
并行计算：https://zh.wikipedia.org/zh-cn/GridMathematica

```
SystemModeler_13.1.0_WIN.iso
SystemModeler_13.1.0_LINUX.iso
SystemModeler_13.1.0_MAC.dmg
gridMathematica_13.1.0_LightweightGridManager_WIN.iso
gridMathematica_13.1.0_LightweightGridManager_LINUX.iso
gridMathematica_13.1.0_LightweightGridManager_MAC.dmg
```

**Comment by TieBaMma** [comment]
SystemModeler有专门的教程：https://tieba.baidu.com/p/5684764548

gridMathematica从来没见人用过，也没见谁放流过，不知道具体啥情况。

**Comment by CNMan** [comment]
还有两个产品
Wolfram Finance Platform
https://www.wolfram.com/finance-platform/
![WFP01](https://user-images.githubusercontent.com/8692234/190386938-28f366ab-30ed-4470-a909-3b8b5564e8da.png)

Wolfram Enterprise Private Cloud (EPC)
https://www.wolfram.com/enterprise-private-cloud/
![EPC03](https://user-images.githubusercontent.com/8692234/190386994-d14e9a1b-7e0d-4e68-86ac-dd7c938c41c3.png)

**Comment by asukaminato0721** [comment]
目前已经镜像，但是没人写介绍。
