### ISSUE TITLE
有没有大佬把《高等应用数学问题的MATLAB求解（第四版）》第3章微积分问题的计算机求解例题翻译成Mathematica？

### ISSUE THREAD

**Issue by CNMan** [TieBaMma/InstallTutorial#108]
http://www.tup.com.cn/booksCenter/book_07749201.html
http://www.tup.com.cn/upload/books/yz/077492-01.pdf

多谢:)

**Comment by TieBaMma** [comment]
……不是，现在贴吧环境是差了点，可你也别把不相关的帖子往这里发啊，你哪怕发到知乎或者MMAQA呢？关了啊。

**Comment by TieBaMma** [comment]
刚大致浏览了一遍，该章节中大部分MATLAB（MuPad？）代码的对应物都可以在自带帮助里轻易找到，专门翻译的意思不大。值得提一下的内容大概有：

1. 按该教程所说，MATLAB（MuPad？）的`limit`在对`x^n`趋于无穷的极限做计算时会自动进行分段讨论（尽管讨论结果有误）。这一点*Mathematica*目前还做不到。（截止版本13.1`Limit`仅会生成一个`ConditionalExpression`——其实也算分段讨论了，但不完整。）因此，若要进行完整讨论，需要设置`Assumptions`选项。
2. 参数方程求导目前尚未内置，但可以用 Wolfram Function Repository 中的`ResourceFunction["ChainD"]`计算。
3. 隐函数求导函数`ImplicitD`已在版本13.1引入。
4. 曲线与曲面积分截至13.1版本依旧无原生支持，对于教学级问题，个人建议还是按教科书给的公式自编。需要注意这两类（四类？）问题的一般化求解其实并不容易。这边有一个第二类曲线积分一般化尝试（其他三类积分在SE上应该也都有一般化尝试，但我一时找不出来）：https://mathematica.stackexchange.com/q/258132/1871
5. 有限差分近似可以使用``NDSolve`FiniteDifferenceDerivative``计算，此函数在自带帮助教程《直线数值方法》中有介绍。
6. 雅克比阵的计算可由`D`函数的第6种语法实现，参看`D`的自带帮助的 范围 -> 向量参数函数，另参：https://mathematica.stackexchange.com/a/5792/1871
