### ISSUE TITLE
新站502了，旧站还活着

### ISSUE THREAD

**Issue by TieBaMma** [TieBaMma/InstallTutorial#110]
@ryaliu 知道是啥情况吗？

如果短时间没法修的话，咱们暂时先把旧站 https://wdm-v2.itsu.eu.org/ 给挂上去？

————

姑且把旧站链接写在了个角落里……

**Comment by ryakuia** [comment]
貌似修好了，我等会改下链接，把旧站作为备用链接加上

---

现任维护者的回复：
> docker没指定 version tag，自动更新到了 alist v3 ，配置文件与 v2 不兼容。v3 的 postgres 也有点问题。已经降级到 v2 了。
