### ISSUE TITLE
WolframEngine_13.2.0_WIN_CN.zip 压缩包损坏

### ISSUE THREAD

**Issue by eoiles** [TieBaMma/InstallTutorial#114]
同时下载了主站
https://wdm.itsu.eu.org/Rasis/WolframEngine/13.2.0.0
和镜像链接
https://wdm-v2.itsu.eu.org/Tairitsu/WolframEngine/13.2.0.0/
都是损坏的,无法解压.
报错如下
![image](https://user-images.githubusercontent.com/24559976/213453232-146fb9aa-24e7-4cf8-93ae-b80d52af0951.png)

**Comment by TieBaMma** [comment]
试了一下，真的是文件损坏…… 这该不会就是 https://github.com/TieBaMma/InstallTutorial/pull/112 里 hash 对不上的真相吧？ @ryaliu

**Comment by ryakuia** [comment]
已经重新搬运，~~请从备线下载（主站有文件缓存，可能需要一会才会显示新文件）~~（Update: 缓存已清除），如果问题解决请关闭这个issue @eoiles 

![image](https://user-images.githubusercontent.com/39220367/213465812-c398cea2-f627-448d-a899-e712354a8a2e.png)


> 试了一下，真的是文件损坏…… 这该不会就是 #112 里 hash 对不上的真相吧？

大概不是。镜像站文件损坏大部分是因为下载/上传过程发生中断，断点续传出错导致的。目前只能依靠用户反馈来纠错。

希望有人可以提供 Mathematica 相关程序的官方 Hash 以便逐一校对。最近 WDM 镜像站已经提供了几乎所有文件的 `md5sum` 和 `b3sum`，如与官方 Hash 不符，请及时反馈，谢谢。
