### ISSUE TITLE
版本9疑似在Win10 22H2 19045.3208版本出现了兼容性问题（内核无法启动）

### ISSUE THREAD

**Issue by TieBaMma** [TieBaMma/InstallTutorial#121]
总算轮到我了嗯，而且丢人的是截止目前我还没搞清楚是怎么回事，姑且在这里记录一下。

总之，推测原因是Win10更新（版本号如标题），症状是版本9无法正常使用。从任务管理器来看，如果直接启动Mathematica并尝试执行任意代码，会看到mathkernel一直在运行；直接启动mathkernel.exe，会发现内核没有正常启动。（In[1]一直未显示。）

Ctrl+Shift再点击mathematica.exe无法解决此问题，重装无法解决此问题。

**Comment by asukaminato0721** [comment]
看了眼发布时间

https://writings.stephenwolfram.com/2012/11/mathematica-9-is-released-today/

猜测是 ms 把某个很老的依赖升级/更改了行为。那我就先在 9 的相关章节里提一句了。

~~要是有日志就好了。~~

**Comment by asukaminato0721** [comment]
感觉不是这里能解决的问题，可能需要去 https://www.wolfram.com/support/contact/ 问一下。
