### ISSUE TITLE
没有14.1

### ISSUE THREAD

**Issue by pbtdej35692hotmail** [TieBaMma/InstallTutorial#140]
没有14.1版本的下载

**Comment by TieBaMma** [comment]
这两帖已经解释了，请仔细阅读：
https://github.com/TieBaMma/InstallTutorial/issues/138
https://github.com/TieBaMma/InstallTutorial/issues/136

**Comment by pbtdej35692hotmail** [comment]
但是没有 Wolfram Engine

**Comment by TieBaMma** [comment]
https://github.com/TieBaMma/InstallTutorial/issues/136#issuecomment-2270239389

**Comment by pbtdej35692hotmail** [comment]
> [#136 (comment)](https://github.com/TieBaMma/InstallTutorial/issues/136#issuecomment-2270239389)
[https://github.com/TieBaMma/InstallTutorial/issues/138](url)
没有Wolfram Engine 14.1 for windows 的下载链接

**Comment by TieBaMma** [comment]
#138 描述部分已改。

**Comment by pbtdej35692hotmail** [comment]
建议将#138 的内容包含在教程里面。
顺便问一下，请问你能提供一下Wolfram Engine 14.1 for windows 的下载链接吗？我用官网的下载器无法下载，谢谢。

**Comment by asukaminato0721** [comment]
> 能提供一下Wolfram Engine 14.1 for windows 的下载链接吗
<https://drive.google.com/drive/folders/1uat0JeKKy7ioZKM2e7qSuiaIfPSVmrSs?usp=sharing>
