### ISSUE TITLE
Mathematica 12 中文 Mac 版镜像

### ISSUE THREAD

**Issue by kinosang** [TieBaMma/InstallTutorial#22]
正版用户，官方的下载器连不上

已经尝试 proxifier 全部劫持，仍不能正常下载

不知道是不是走了 UDP 还是怎样

有没有人下载好了可以共享一下，或者有没有官方非下载器的链接 😂

**Comment by TieBaMma** [comment]
我觉得这个是不是可以找客服……毕竟买了正版，找他们也是理直气壮。

**Comment by kinosang** [comment]
@TieBaMma 谢谢，已经联系过客服了，目前还没有回应

**Comment by zhouyiji** [comment]
我也是，download manager真的太坑了。请问 @TieBaMma 能否提供镜像下载呢？感谢

**Comment by kinosang** [comment]
@TieBaMma @zhouyiji 官方提供了 dmg 下载链接给我，我转存分享一下

Mathematica 12 Mac 中文 https://mega.nz/#!NABX3CrZ!aYzt6S2XeWkJvSdi7JhswfARlyfxV3GcivnND7cRL2s

Wolfram Engine 12 Mac https://mega.nz/#!BBp0GYzC!gctafZxbL57kNPUXiOLnR1ETpHQ8DNTp-CJzgdhFPYY

*不保证链接长期有效*

**Comment by RaffeYang** [comment]
我也是正版用户，我除了Mathematica 12 ，新出的Wolfram Engine 还有Wolframalpha Notebook也是一样的mac版本无法下载，windows版本正常。官方的download manager完全没法在mac使用

**Comment by kinosang** [comment]
@Jax0rz  Mathematica 和 Engine 我已经转存到 mega了，链接见上面

notebook 你可以发邮件给官方客服要 direct link
