### ISSUE TITLE
Mathematica 12.0 Mac 版百度网盘链接更换

### ISSUE THREAD

**Issue by asukaminato0721** [TieBaMma/InstallTutorial#24]
刚刚注意到提交的 Pr 里的链接是有时限的。
又转存了一份永久的。
https://pan.baidu.com/s/18M5m9qBKyrNQNfm0xcvd8Q
提取码 1234

**Comment by TieBaMma** [comment]
已加入。（这次咋没有直接提交？）

**Comment by asukaminato0721** [comment]
因为我 GitHub 用得还不熟，😂，很多功能还在学习中。只能先用自己学会的技能解决问题。
