### ISSUE TITLE
Mathematica_12.1.0 奶牛盘镜像文件打不开

### ISSUE THREAD

**Issue by jinyiliu** [TieBaMma/InstallTutorial#29]
打不开奶牛盘的镜像文件，一直提示资源忙，下载过两次，确认下载 dmg 从大小上来看是没问题的（5.26G）
奶牛盘下载还需要付钱，好肉痛啊！>_<
<img width="484" alt="截屏2020-04-05 下午2 39 29" src="https://user-images.githubusercontent.com/23398808/78468981-3d224800-774f-11ea-81b3-fa2297bde31e.png">

**Comment by Lemmingh** [comment]
cc. @wuyudi

**Comment by jinyiliu** [comment]
虽然不知道为什么，但是重启之后问题就奇妙地解决了。谢谢你们！

**Comment by jinyiliu** [comment]
虽然不知道为什么，但是重启之后问题就奇妙地解决了。谢谢你们！❤️

**Comment by Lemmingh** [comment]
'Resource busy' 应该是 macOS 自己的问题，而且常常较难判断究竟是哪个程序占用了它。既然重启能释放，那么应该问题不大。
