### ISSUE TITLE
添加 license

### ISSUE THREAD

**Issue by TieBaMma** [TieBaMma/InstallTutorial#30]
@Lemmingh  建议给教程加个license：

> 
> ‘license’ 可以翻译为“授权”“许可”“协议”之类的。
> 
> 它算是个合同，用于处理法律问题。比如 owner 与 contributor 之间的关系，developer 与 user 之间的关系。
> 
> 长远来看，license 是每个项目必需的，它可以划清一些责、权，避免相关纠纷。
> 
> 这个项目可以考虑 CC BY 4.0，或者 CC0 “送给” public domain 也行。[CC Australia 制作的指南](http://creativecommons.org.au/content/licensing-flowchart.pdf)也许有帮助。
>  
> 我还是希望 CC BY ——至少留个名字。
> 

不过这个我确实不太懂，所以，大家怎么看？

链接似乎失效，新 [link](https://au.creativecommons.net/choose-a-licence/)

**Comment by asukaminato0721** [comment]
https://chooser-beta.creativecommons.org/

> 至少留个名字。

---

下面是一些选择

- use your work commercially?  mma 本身就是商业软件。
- allow others to remix, adapt, or build upon your work? 当然可以 adapt
- allow others to share adaptations of your work under any terms? 反正留了署名权

于是就先

> This work is licensed under CC BY 4.0
