### ISSUE TITLE
将来安装包放哪里

### ISSUE THREAD

**Issue by specter119** [TieBaMma/InstallTutorial#33]
百度云下不动，开了会员转瞬又被限速了。
linux 12.1.0 mega上有个资源，但是下下来 md5sum 不太对，有个地方deb解包解不开。
bt 磁力，mega 我觉得都还好，百度云现在是太坑了。

**Comment by TieBaMma** [comment]
但是mega在国内下不动……话说你如果看编辑历史会发现大家在这方面做过不少尝试，最后还是百度盘长青……

**Comment by Lemmingh** [comment]
很高兴有人关注**存储服务、文件分享方案**方面的问题。

这个项目的特点，在很大程度上限制了选项。总的来说，理想的解决方案是~~海量廉价高带宽大流量存储服务~~（~~本地硬盘~~做梦）。

* 下载地址列表相当于给 Wolfram 做镜像，需要大量的存储空间，而且消耗相当快。
  * Mathematica 的安装文件已经长到每个 4 GB。集齐 3 个平台就是 12 GB。
  * 经常要同时收集中、英文 2 套。
  * 平均每 2 年发布一代新产品。中间会发布多个小版本。
  * 历史版本基本没人看，但还得留着。
* 一个完全靠兴趣、完全不盈利、完全不商业的社区，用不起任何烧钱的服务。
  * 如果只是稍微花点钱，就看贡献者的意向了。现在，许多下载地址就是由编辑者独立维护的。

以下是我能想到的。

## 候选

> **说明**
>
> * 描述存储空间，在确凿的情况下，用二进制词头的单位。
> * 描述传输速率，用十进制词头的单位。
> * 区分“限速”和“限流量”。

* [百度网盘](https://pan.baidu.com/)
  * 空间很大、价格极低。
  * 限速极严、审核成谜。
* [天翼云盘](https://cloud.189.cn/)
  * 定位是家庭云存储。分为个人空间、家庭空间两部分。个人空间的文件可以对外分享，家庭空间的不能。文件可在个人、家庭、企业之间转存。
  * 天翼云似乎使用十进制词头的单位来计算空间。
  * 下载
    * 下载大于 300 MB 的文件需要登录天翼账号（用手机号注册，电信号已默认分配，可以注销），只需装个手机客户端，扫码登录。
    * 无明显限制。至少电信用户速度很快，起步 几 MB/s。联通也不差。其他线路就难说了。
    * *传说*未来可能限流量，不知是什么情况。
  * 上传
    * ~~早期用户的初始空间只有 10 GB。曾经大规模送空间。~~ 现在只能从基础 30 GB 开始积累。
    * 每日签到、抽红包可获得约 50~100 MB 个人空间。坚持 2 个月，就能攒出一个镜像的空间。
    * 普通用户，空间 30+30 GB，限制上传量 2 GB/天，免费。
    * 黄金会员，空间 4+2 TB，限制上传量 200 GB/天，¥19 /月。
    * 铂金会员，空间 4+4 TB，不限流量，¥40 /月。
    * 无明显限速。
    * 有一套似乎很宽松的分享审核。
* [蓝奏云](https://www.lanzou.com/)
  * 下载
    * 无限制，很快。
    * 偶尔服务中断，我猜是有 DNS 污染。按官方的说法，部分地区运营商下无法访问，需要分享者设置个性化域名（`xxx.lanzous.com` 的格式）。其实，只要**访客**在 `xxx` 部分随便输个不是 `www` 的玩意就能接通（泛解析）。
  * 上传
    * 不限空间。
    * 不限速。
    * 限制上传类型（扩展名），于是，有时需要改文件名。
    * 会员可以付费去除下载页面的广告。
    * 限制单个文件大小：
      * 普通，100 MiB。
      * V1，110 MiB，¥15 /月。
      * V2，160 MiB，¥29 /月。
      * V3，210 MiB，¥69 /月。
      * V4，不限大小，按流量计费 ¥0.09 /GiB。
* SharePoint / OneDrive for Business
  * Microsoft 推出的商业解决方案。在中国，分为“全球版”“世纪互联中国版”两种。（在世界范围内就更[复杂](https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/office-365-plan-options)了。）
  * Microsoft 365 （曾用名 Office 365）的定价很繁杂，有时，[买 Office](https://www.microsoft.com/zh-cn/microsoft-365/compare-all-microsoft-365-products?activetab=tab:primaryr2) *可能*比[单订 OneDrive](https://www.microsoft.com/zh-cn/microsoft-365/onedrive/compare-onedrive-plans?activetab=tab:primaryr2) 合算。😂
  * 管理员的权限很大，能控制公司内所有账户。
  * 下载
    * 全球版，大陆下载 几百 kB/s，高峰期会慢很多，如果翻出去则能稳定在 几 MB/s。
  * 上传
    * 全球版，大陆上传 1~3 MB/s。
    * 商业 [Microsoft 365 Business Basic](https://www.microsoft.com/zh-cn/microsoft-365/business/microsoft-365-business-basic) (Office 365 Business Essentials) 授权，自定义席位，每人初始 1 TiB OneDrive，和大部分在线服务，¥36.00 /用户/月（包年）。
    * [凭 edu 邮箱](https://www.microsoft.com/zh-cn/education/products/office)可以获得 1 个免费的[教育 A1](https://www.microsoft.com/microsoft-365/academic/compare-office-365-education-plans) 授权，有 1 TiB OneDrive，和大部分在线服务。如果学校已经统一购买了 Microsoft 365，则前面那个链接会激活学校订购的 Office 365 Education。
    * 另外，Microsoft 365 默认的[密码过期策略](https://docs.microsoft.com/microsoft-365/admin/manage/set-password-expiration-policy)（管理员可调整）为 3 个月，即每 3 个月需要改一次密码，虽然不改也能接着用，但很多服务要求先改密码才能访问。
* [奶牛快传](https://cowtransfer.com/)
  * 速度很快。
  * 上传和下载都要[付费（说贵不贵，说便宜不便宜）](https://sspai.com/item/81)。
* P2P (magnet, BT, etc.)
  * 完全依赖 P2P 网络、社区。
  * 一些地区封锁 P2P。
* [腾讯微云](https://www.weiyun.com/)
  * 迷惑现象比百度云少。
  * 下载
    * 免费版，下载限速 100 kB/s，可以规避。（文档里是 `100KB/s`，不晓得是什么意思）
    * 超级会员，无限制。
  * 上传
    * 付费体系比较复杂。分为“超级会员”“仅购买存储空间”这两大类。会员区分等级 LV1 ~ LV8。不同时长的订阅的单价不同。
    * 免费版，空间 10 GiB，上传限速限量（我通常用“同步助手”，也没有传过很大的文件，无感受）。
    * [超级会员](https://www.weiyun.com/vip/privilege) LV1，空间 6 TiB (6144 GiB)，限制上传量 40 GiB/天（达量降速），
      * ¥19 /月（连续包月）
      * ¥18 /月（连续包年）
      * ¥24 /月（12 个月）
      * ¥28 /月（6 个月）
      * ¥30 /月（3 个月）。
    * 存储空间 1024 GiB，¥600 /年（¥50 /月）。
    * 存储空间 200 GiB，¥218 /年（¥18.2 /月）。
    * 存储空间 50 GiB，¥78 /年（¥6.5 /月）。

## 排除

* [MEGA](https://mega.nz/)
  * [大陆连接困难](https://www.jianshu.com/p/44741a9e243f)。
* ……
  * 大陆连接困难，或者没有合适的方案。

**Comment by wuyudi** [comment]
微云的下载可以用[这个](https://www.jianzxs.com/157.html)解决：
TLDR 版：微云发给自己的小号。然后在 QQ 或 Tim 下，速度很快。

几个思路：

1. 用 QQ 群来存(最新)安装包。一个群可以放 10g 的文件，下载速度可以参考[这个](https://jingyan.baidu.com/article/f7ff0bfc26273a2e26bb13da.html), 可以直接设置全体禁言,下完自动退群. 或者直接[开放游客权限](https://jingyan.baidu.com/article/acf728fd5efeacf8e510a3d2.html)，这样不用担心人数问题了。以及[单个人能创建的群数](https://zhidao.baidu.com/question/1435477267798047419.html)

2. Telegram 群组无限容量，速度可以，最高 20w 人/群。但是单文件限制 1.5 g（分卷压缩），而且可以采用广播的形式，那样能第一时间看到更新。

> 能分享文件的未必是网盘 🤣

**Comment by specter119** [comment]
> 微云的下载可以用[这个](https://www.jianzxs.com/157.html)解决：
> TLDR 版：微云发给自己的小号。然后在 QQ 或 Tim 下，速度很快。
> 
> 几个思路：
> 
> 1. 用 QQ 群来存(最新)安装包。一个群可以放 10g 的文件，下载速度可以参考[这个](https://jingyan.baidu.com/article/f7ff0bfc26273a2e26bb13da.html), 可以直接设置全体禁言,下完自动退群. 或者直接[开放游客权限](https://jingyan.baidu.com/article/acf728fd5efeacf8e510a3d2.html)，这样不用担心人数问题了。以及[单个人能创建的群数](https://zhidao.baidu.com/question/1435477267798047419.html)
> 2. Telegram 群组无限容量，速度可以，最高 20w 人/群。但是单文件限制 1.5 g（分卷压缩），而且可以采用广播的形式，那样能第一时间看到更新。
> 
> > 能分享文件的未必是网盘 🤣

TG 确实无限空间，但是也有访问的问题。

**Comment by Lemmingh** [comment]
微云最大的问题是上、下**都限速**。虽然可以利于 QQ 中转来规避。
不一定要开小号：QQ PC 端可以在“联系人”中找到自己，开个即时消息窗口，给自己发消息。

微云的免费空间只有 10 GiB，搁 2 个 MMA 镜像就满了。而微云的设计又不太令人满意，如果对它没感情，就不愿意掏钱买会员。

---

从**隐私保护**的角度看，我反对 QQ 群。

这个项目源自贴吧，全网公开，访客鱼龙混杂。目前的发布措施，包括 GitHub，对参与者的隐私能有较好的保护，即使有闲人去翻 log，也拿不到太多有价值的信息。
而 QQ 是一爆一个准，即使专门开个小号，也不见得靠谱。

QQ 群更适合熟识或者明显可控的圈子。

---

如果不加约束条件，放眼全球，方案确实多。

但依次考虑

1. 大陆可**直连**
2. 空间够大
3. 价格低
4. 速度快
5. 访客可能理解力不佳

这几个方面后，情况就棘手得很。

**Comment by ryakuia** [comment]
我再提供几个好了

* Google 云端硬盘 + GoIndex
  * 走 Cloudflare 反代，国内可以访问，但是速度基本看脸（10KB/s ~ 5000KB/s 都有可能）。
  * 可以用学校团队盘，空间很大。

* FODI 或 OneManager-PHP + SharePoint 或 OneDrive
  * 可以直接复制链接走 Aria2 IDM （仅 OneManager-PHP）。
  * 可以解决微软部分限制（比如强制登陆），也可以解决大陆访问 SharePoint 时有白屏、 OneDrive 个人版被墙的问题。
  * 下载还是走微软服务器，下载速度约为 500KB/s。
  * [示例](https://mmamirror.herokuapp.com/) 

* 超星云盘
  * 比较冷门。
  * 每个文件最大 1G，每人150G 存储空间。
  * 不限速，体验还可以。
  * 每个文件限制 1GB ，得分卷（但是没有蓝奏那么麻烦）。
  * 需要国内手机号注册。

我觉得 TG 存文件是个比较方便的方法（但是得翻墙）。[示例](https://t.me/s/mmalanguage) （这个示例频道不知道为什么不能在线预览）

本人不对以上示例文件负责。

**Comment by ryakuia** [comment]
另外天翼云盘并不是不限速……免费用户分享链接下载的时候对单线程限速，而且这玩意下载链接传递了cookies……我昨天晚上挂着下了一晚上，今天早上80%，结果过了半个小时断网了……后来拿Aria2跑16线程跑到了 1.8MiB/s。

我在我的PR #42 里提到了免登陆下载的方法，读了下js源码，天翼网盘判断是否登陆貌似是在浏览器完成的，于是就可以绕过了。

腾讯微云对于我这样的 Linux 用户（没充钱）很不友好，还经常断线，网页版不能断点续传（Aria2 好像可以，没试过）。

**Comment by specter119** [comment]
感觉 SharePoint 用 IDM 下载还是很稳的。

**Comment by ryakuia** [comment]
> 免费版，下载限速 100 kB/s，可以规避。（文档里是 100KB/s，不晓得是什么意思）

实测是 100KiB/s ，不算快，但比100kb/s 快了不少（8倍的差距，233333）

**Comment by cirnovsky** [comment]
曲奇网盘可以考虑吧，2T空间不限速

**Comment by Lemmingh** [comment]
曲奇网盘……我记得限制文件大小，小文件可以。**谁去确认一下**？

**办公向的服务**一般都有些奇妙的限制措施以防滥用。

**Comment by Lemmingh** [comment]
@TieBaMma

Issue title 改成“**将来安装包放哪里**”如何？

**Comment by ryakuia** [comment]
继续更新

- [Degoo](https://www.degoo.com)
  - 才发现的冷门云盘，主打手机照片备份，但是有分享功能。
  - 免费 100G ，可以通过邀请别人注册的方式增加免费容量，每邀请一个人增加 5G。上限初始100G + 邀请500G，如果走邀请链接注册再加 5G。
  - 国内直连速度可以达到 2MiB/s 。
  - 免费套餐最大文件 512MiB。

- [Office 365 由世纪互联运营](https://www.microsoft.com/zh-cn/microsoft-365/compare-china-global-versions-microsoft-365)
  - 国内服务器，下载速度快，比国际版 Office (OneDrive) 快多了。
  - 相对而言比较贵（但是空间大体验好）。
  - 避坑提醒：别买 F3 订阅，贪小便宜结果巨坑无比。最便宜的有 1T 云储存体验的订阅是 SharePoint 计划1（注：使用SharePoint 网站空间），有 5T OneDrive 体验的是商业基础版，都得300大洋以上还有 6% 税。~~用爱发电~~

- [白猫网盘](http://whitecats.dip.jp/up/)
  - 日本的网盘，免注册即可上传
  - 最大文件限制 100G
  - 未测试速度

**Comment by ryakuia** [comment]
（省流：WDM 可能将会关站。需要寻找新的文件存储方案。） @TieBaMma 

WDM Mirror 发了一篇 [WDM 站点情况与未来计划](https://wdm.itsu.eu.org/cl.html)，但是现在 InstallTutorial 里几乎没有其他的下载源了。现在急需寻找其他的文件储存方案。

之前使用 IPFS 的尝试算是失败了，本页的大部分储存服务也并不合适。

**Comment by TieBaMma** [comment]
![P_8832%S1AT25)VOQC4T~8U](https://github.com/TieBaMma/InstallTutorial/assets/21972695/0a08f614-9166-4394-a562-c543b5e81437)只能先搬回百度盘了，明天应该能抽点时间出来先搞下最新版的百度盘下载。话说关站公告页面怎么还带彩蛋的。

----------

![PMBL6XP$9Z H(8)NPR 5EV](https://github.com/TieBaMma/InstallTutorial/assets/21972695/0e5b05f4-66a2-4e87-837a-c827ecde8bd7)或者我们直接放官网地址？：https://www.wolfram.com/download-center/mathematica/ 反正现在官方也不藏着了。（我记得老早的时候，想下载是必须申请试用的？）

-----------

13.2.1版百度盘下载链已补上。

**Comment by asukaminato0721** [comment]
经过和某位反复讨论，目前是采用 web seed https://askubuntu.com/questions/313107/what-is-web-seed 的方式。

在多台机子上测试下载都能成功。然后也有共享率。

![image](https://github.com/TieBaMma/InstallTutorial/assets/30024051/ad91e373-bf66-4ec6-9608-3caf696c4c55)

**Comment by asukaminato0721** [comment]
目前在把历史版本也做成 web seed. 这个问题应该可以 close 了。
