### ISSUE TITLE
基于 JavaScript 的注册机

### ISSUE THREAD

**Issue by AlbertLei** [TieBaMma/InstallTutorial#35]
补充一个在 mac 下不用安装注册机的方法, 亲测可用: [mathematica-keygen](https://www.npmjs.com/package/mathematica-keygen). 
缺点是得安装 node/npm. 优点是不用找 windows 电脑安装注册机...

**Comment by Lemmingh** [comment]
感谢您的建议。

看上去，这是一个用 JavaScript 编写的注册机，且没有依赖 node API，可以在浏览器里跑。

~~冒昧的问一下，它跟 [Wolfram Mathematica 12 Key Generator Online](https://ibugone.com/blog/2019/05/mathematica-keygen/) 有什么区别？~~

我觉着，可以写进正文。
