### ISSUE TITLE
12.1 OneDrive链接已失效

### ISSUE THREAD

**Issue by cbwang2016** [TieBaMma/InstallTutorial#36]
![image](https://user-images.githubusercontent.com/18070081/80308001-1a8bc800-87ff-11ea-9758-dbc0986a4845.png)
![image](https://user-images.githubusercontent.com/18070081/80308006-24153000-87ff-11ea-8d52-01c0d4d7aca9.png)

**Comment by Lemmingh** [comment]
@wuyudi , 请问 wxyh 那边出什么状况了吗？

**Comment by asukaminato0721** [comment]
1. 对方换域名了，而且说最近一阵子不会稳定下来。
2. 我打算自己分享 OneDrive. 但是试了很久没有成功 
3. 参考[这个](https://zhuanlan.zhihu.com/p/74538287)最后一步失败了
4. 后面打算直接分享[外链](https://mapaler.github.io/GetOneDriveDirectLink/)，但是也不成功。估计是操作不对？

直接共享得到的链接我放在下面了。不知道能不能用。如果能的话我就 pr 了。

<https://hii9w-my.sharepoint.com/:f:/g/personal/wuyudi_od_wulel_com/Ej7u-BSKTj9Jj-fMyUpsrn0BWuD75BrMXzZE350mst2w3g?e=VsKpq2>

**Comment by Lemmingh** [comment]
* 知乎上的方法，可能有利于隐藏真实地址。不过，我个人认为意义不大。
* <https://mapaler.github.io/GetOneDriveDirectLink/> 上的方法面向 OneDrive **Personal**，而你的是 OneDrive **for Business**，自然行不通。
* 就大陆的网络情况，我更倾向于以后用[天翼云](https://github.com/TieBaMma/InstallTutorial/issues/33#issuecomment-626136160)存镜像，光免费版就能凑合几年。
