### ISSUE TITLE
介绍运行代码的替代方案，如 tio.run

### ISSUE THREAD

**Issue by asukaminato0721** [TieBaMma/InstallTutorial#43]
因为 Mathematica 有点大，而一些用户可能就是偶尔用用。所以有个在线运行的应该会方便些？

链接：https://tio.run/#mathematica

简易使用方法

1. 点一下 Hello World
2. 在 Code 里输入代码。
3. 点上面播放键

![image](https://user-images.githubusercontent.com/30024051/82879358-5c0db100-9f2c-11ea-8617-540c0b39e953.png)

好处：
1. Wolfram Cloud 速度慢，这个相对较快
2. 一直是最新版，可以 `$Version` 确认

缺点：
1. 就是纯 txt
2. 60s 计算限时
3. 不支持图片
4. 没有拓展性

> 临时用用也足够了

**Comment by TieBaMma** [comment]
可以吧。甚至可以考虑加一个“在线Mathematica”小节。这个少说也是季经问题。

**Comment by asukaminato0721** [comment]
我觉得可以叫做 Mathematica(Notebook) 的临时替代品（要求是语法和 Mathematica 一致）
目前我知道这几个：
1. Mathics
    - 好处:
        1. 基于纯 Python, 免费
    - 坏处:
        1. 停更很久了，版本过老（可能很多函数不支持）
2. tio.run
3. Wolfram Cloud
    - 好处:
        1. 免费
    - 坏处:
        1. 速度感人

**Comment by asukaminato0721** [comment]
现在问题是怎么安排格式？比如这段安排在哪？该怎么写？这方面我不熟。 @Lemmingh

**Comment by TieBaMma** [comment]
还有一个值得考虑的点是，Wolfram Cloud Android apk下载地址要不要也附上。（我个人是一直反对在手机上弄Mathematica的，而且这个apk使用体验真的是极差。）

**Comment by wuyudi** [comment]
test, 不知道这个能不能发成功。


http://rdstf4bw.gic.cnbj01.cdsgss.com/browser/content_input.action?fileName=


这个是官方仓库。













在 2020-05-30 12:15:58，"TieBaMma" <notifications@github.com> 写道：

还有一个值得考虑的点是，Wolfram Cloud Android apk下载地址要不要也附上。（我个人是一直反对在手机上弄Mathematica的，而且这个apk使用体验真的是极差。）

**Comment by Lemmingh** [comment]
> 怎么安排？

标题取为“**在线 Wolfram 计算的方法**”如何？

总体看，它们都是处理 Wolfram Language，在线进行计算。

---

按照现在的目录

1. Wolfram Engine for Developers
2. {A}
3. Mathematica 软件下载
4. Mathematica 软件的激活
5. Mathematica 入门
6. 安装激活 Mathematica 时可能碰到的问题

如果放在主页（目前也仅有主页），只能插在 {A} 处。毕竟后面那些承接很紧密。

也可以[单独写篇文章](https://jekyllrb.com/docs/pages/)。不过，这样又出来许多要处理的事情。

---

我简单看了 [Wolfram Cloud](https://www.wolfram.com/cloud/) 的介绍。还在 [Docker Hub](https://hub.docker.com/search?q=wolfram&type=image) 上发现了 [arnoudbuzing/wolframengine](https://hub.docker.com/r/arnoudbuzing/wolframengine)。

看来，潜在的玩法很多，写一长篇不成问题。
