### ISSUE TITLE
和 Wolfram 官方人员的交流

### ISSUE THREAD

**Issue by asukaminato0721** [TieBaMma/InstallTutorial#44]
这件事留给各位“苦恼”吧😂
我报了 [Wolfram 大使](https://www.wolfram.com/company/careers/ambassador/index.html.zh?footer=lang)，刚刚面试了，在面试中提到这个项目<del>（感觉有点作）</del>
以下是我要说的：

1. 有个 issue/pr 放了 Wolfram 官方的仓库的链接（确认是官方仓库了），这里不链接了，上面放了很多东西。希望链接地址别大范围传播（感觉言外之意是单文件的链接可以？😅，应该类似分享单文件 / 分享整个目录），这样新安装包的获取就会比较方便了（也方便网盘分流）

2. 对于这个项目,面试官隐晦地表达了一些情绪.

> 本来想弄个萌百那种黑色背景，选择显示的效果，结果根据这个 https://github.com/github/markup/issues/369 Github 不支持，只能作罢。

 然后请 @Lemmingh 和 @TieBaMma 来决定吧😅，比如那个 pr 要不要修改什么的。

> 我的观点是[这个](http://www.ruanyifeng.com/blog/2012/12/minecraft_the_story_of_mojang.html)

**Comment by Lemmingh** [comment]
这次轮到我听不懂你们在说什么了。😳

---

> Wolfram 官方的仓库的链接

如果你认为那属于敏感、隐私信息，尽管删掉。GitHub 提供[删除编辑历史](https://help.github.com/en/articles/tracking-changes-in-a-comment)的功能就是为了这种场景。~~但是发出去的邮件收不回来。~~

企业存储属于公司的财产，尽量能保密就保密。我的建议是，你可以从那里下载安装文件，再传到自己的存储服务，分发自己的链接。

---

> 面试官隐晦地表达了一些情绪

可能是对“激活”那部分不满意？

社区文档不是稀罕事，不至于触动他。镜像下载符合大陆现实，解释解释应该也能接受。

我曾经设想，也许未来有一天，为了规避 DMCA，这个项目需要删些东西。但没想到还有更快的事情。😅

---

> 萌百那种黑色背景……但是 Github 不支持

GitHub 的 sanitization 很严格，现在似乎是把所有 HTML tag 都过滤掉。

我认为，[黑幕](https://zh.moegirl.org/Template:%E9%BB%91%E5%B9%95)可能更会引起读者的好奇，不如若无其事。

**Comment by asukaminato0721** [comment]
感谢建议，history 已删。链接已存。

**Comment by TieBaMma** [comment]
近段时间都是直接上的github，结果反而没看到这个issue，今天久违地查了下邮箱才发现……近期pr的链接我也没专门备份，感觉好像亏亿了？

**Comment by Lemmingh** [comment]
[Notification settings](https://github.com/settings/notifications) 可以调嘛。

我是所有消息都发邮件。同时，Participating 也推 GitHub 站内通知，这样方便处理急事。

**Comment by ryakuia** [comment]
#45 的短链接最好也删掉吧……

**Comment by asukaminato0721** [comment]
> #45 的短链接最好也删掉吧……

已删，然后被 quote 的那张图我没法删😅。有劳了。
