### ISSUE TITLE
(12.1.0) Windows 中文 + Mac 中文  下载不了

### ISSUE THREAD

**Issue by mengjincn** [TieBaMma/InstallTutorial#45]
(12.1.0) Windows 中文 + Mac 中文 下面的SharePoint链接点开需要登陆，无法下载。能否提供个可以直接下载的链接？比如放在蓝奏云

**Comment by Lemmingh** [comment]
cc. @wuyudi

**Comment by Lemmingh** [comment]
感谢您的报告。

Mathematica 的安装文件已经**超过**每个 4 GB。蓝奏云不合适。
#33 正在讨论相关问题。

**Comment by asukaminato0721** [comment]
目前官方给的下载方法是：
1. 通过 user.wolfram.com 登录下载（前提是你买了）
2. 通过官方之前流出的仓库下载。但是官方人员说仓库地址本身不要大范围宣传。而文件链接本身带了地址。所以还是得靠分流，就又回到存储这个老问题了。

或许可以试试短网址？理论上只有下载时会出现原链接，估计没有人注意。

**Comment by Lemmingh** [comment]
> 理论上只有下载时会出现原链接

👀阅后即焚？
救急的场合，发个定时销毁的链接可能是个好办法。

**Comment by wuyudi** [comment]
意思是，点开后会出来
![image](https://user-images.githubusercontent.com/30024051/83087787-a48ab300-a081-11ea-89e9-8f035db51de9.png)
但是应该没人会特意去注意链接。所以应该可行。

**Comment by ryakuia** [comment]
> 意思是，点开后会出来
> 
> 但是应该没人会特意去注意链接。所以应该可行。

我觉得官方的意思“不要公开传这个仓库”是说包括短网址都是不允许的…

我试试周末（咕咕咕警告）把mac版搬到我的 SharePoint （使用API获取下载链接）上，这样可以解决部分问题。

**Comment by Lemmingh** [comment]
> 意思是，点开后会出来

是我想多了。我以为这链接能够定时自毁。

我能明白你的意思（重定向会到达原始地址），不必放图。

我赞同 **ryaliu**。我的建议是，**以后请不要让这些东西出现在公开区域**。记得回来删除敏感信息。

cc. @TieBaMma

**Comment by Lemmingh** [comment]
https://github.com/TieBaMma/InstallTutorial/blob/25b053bb98be7a12c4468a19e96734396f7aa21c/index.md#L146-L147

@wuyudi
这个地址仍然存在权限问题。可否检查一下？谢谢。

**Comment by asukaminato0721** [comment]
仔细看了下，回想起来了，这是群友提供的下载链接（我说怎么会没权限了

已私信询问。
