### ISSUE TITLE
12.1 Linux 中文版 arch aur安装解包错误

### ISSUE THREAD

**Issue by specter119** [TieBaMma/InstallTutorial#47]
我已经删除 sh 源文件了，所以现在没法对比 hash 了。
冒昧问下，12.1 Linux 中文版是从官方下载的么？因为我之前辗转下12.1英文版的时候，也下载了多个版本hash对不上(相比[aur里的英文版](https://aur.archlinux.org/packages/mathematica/))，忽略hash检查安装会因deb解包错误失败，最后官网开了试用才安装成功。
这次12.1中文版我想试着重新装下，但也遇到安装过程中报deb解包解不开的错误而停止安装。

> 不过不怎么影响，把 windows 那边的 Documentation 目录全拷过来也就成中文版了。

还有，没有订阅的话，可以查到hash么？下载地址里的hash是从官网粘过来的么？

**Comment by ryakuia** [comment]
Linux版啥时候是deb了，不是个sh包了个压缩包吗？

官方貌似没给大文件的hash，提供者得自己算

**Comment by specter119** [comment]
> Linux版啥时候是deb了，不是个sh包了个压缩包吗？

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mathematica#n160
解开了还是有deb，我现在Arch所有遇到的装不上都发生在解deb这步。

**Comment by Lemmingh** [comment]
看上去，SharePoint 上存的 `MMA_12.1.0_Linux_zh_CN.sh` 与天翼上存的 `Mathematica_12.1.0_Chinese_LINUX.sh` 是同一个文件。再考虑到 @wuyudi 能访问官方仓库。我猜是官方版本。

---

FYI:

印象中，官方仓库里，12.1.0 版每个平台都有两套包：

* `Mathematica_12.1.0_Chinese_<platform>_CN`
* `Mathematica_12.1.0_<platform>_CN`

带有 `Chinese` 的那个略大一些。目前不清楚是什么区别。

**Comment by specter119** [comment]
如果确实是官方版本，那就很尴尬了，AUR 使用中文的12.1没法安装。

> 带有 `Chinese` 的那个略大一些。目前不清楚是什么区别。

```
/opt/Mat/Documentation> du -h --max-depth=1
6.7G    ./English
6.8G    ./ChineseSimplified
```
或许是文档大了那么一丢丢(上面两个目录均为12.1文档，中文的是从window复制过来，使用没问题)。

**Comment by ryakuia** [comment]
你试试不用AUR，直接运行.sh

我猜是12.1中文版改了文件结构，AUR脚本不支持

另外AUR里面的md5肯定对不上啊…一个中文版一个英文版，md5怎么可能相同…

**Comment by specter119** [comment]
> 另外AUR里面的md5肯定对不上啊…一个中文版一个英文版，md5怎么可能相同…

我上面说的是，之前下的英文版md5对不上，中文版的肯定应该不一样。
过几天我重下一会，直接用sh安装一次试试。

**Comment by ryakuia** [comment]
> > 另外AUR里面的md5肯定对不上啊…一个中文版一个英文版，md5怎么可能相同…
> 
> 我上面说的是，之前下的英文版md5对不上，中文版的肯定应该不一样。

嗯……我看来要重修语文了

Debian 和 CentOS 都试了，可以正常安装，手头没Arch Linux 没法复现

**Comment by specter119** [comment]
相对于英文版, deb 的文件名改了，我的锅，deb文件名和日期相关。我也明白前几个 hash 不对的版本是咋回事了，可能小版本号不同，日期不同，deb文件名也不同。
我的锅，抱歉，顺便建议aur那边把文件名改宽。
