### ISSUE TITLE
SharePoint-API 应该放文件夹链接还是文件链接

### ISSUE THREAD

**Issue by ryakuia** [TieBaMma/InstallTutorial#48]
* 文件夹链接

  预览 <https://mmamirror.herokuapp.com/%E5%AE%89%E8%A3%85%E5%8C%85/12.1/>

  优点：

  * 一个文件夹放一堆东西，不需要每次添加文件就在这边提交PR。
  * 可以放个 hash.txt ，也可以直接在页面上加有关说明（见“预览”），上方和下方都有附加说明。

* 文件链接

  例子 <https://mmamirror.herokuapp.com/%E5%AE%89%E8%A3%85%E5%8C%85/12.1/MMA_12.1.0_Linux_zh_CN.sh>

  优点：

  * 可以直接加入 Aria2 IDM 等下载。
  * 用户不需要跳转到文件夹再点击具体文件，节省一点时间。

  缺点
  
  * ~~就是文件夹链接的优点反过来，懒得写了~~

***

以上两种方式，哪一个更适合放在本项目中？

***

私货：搬运其实也挺费时间的……有没有人愿意帮忙搬呢（我会私发一个上传入口）。

如果微软赏脸给我长时间续期的话，这个镜像应该是不会取消的。

**Comment by Lemmingh** [comment]
# 关于向 SharePoint / OneDrive 搬运

可以调 API 向 SharePoint 传文件。要注意，[不能操作太频繁](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online)。

如果能实现自动化下载原始文件，那么搁云端跑即可。（如果服务费比电费便宜。）

* [Uploading Large Files using Microsoft Graph API | Adam Burns | Microsoft Tech Community](https://techcommunity.microsoft.com/t5/sharepoint-developer-blog/uploading-large-files-using-microsoft-graph-api/ba-p/510041)
* [Upload contents for an item on OneDrive | OneDrive API | Microsoft Docs](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/upload)
* [Upload large files | Microsoft Graph REST API v1.0 | Microsoft Docs](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession)
* [Upload a file | SharePoint REST API v1 | Microsoft Docs](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery)
* [SpRestLib - a lightweight wrapper around the SharePoint REST API](https://gitbrent.github.io/SpRestLib/)

**Comment by ryakuia** [comment]
上传走微软 OneDrive for Business 原生页面，走API上传太蛋疼了……

目前我是Serverless，Heroku 的 TOS 明确禁止了作离线下载器的行为…
