### ISSUE TITLE
宣传 Wolfram 学生大使计划

### ISSUE THREAD

**Issue by asukaminato0721** [TieBaMma/InstallTutorial#57]
因为我不知道这个内容应该加在哪，就开个 issue 先。

网址 https://www.wolfram.com/company/careers/ambassador/index.html.zh?footer=lang

可以获得的：wolfram 系列产品全解锁

需要做的：

1. 需要准备一份简历。这个不用太在意。
2. 会有个简单的面试，是中文面试。
3. 每个月填个表说明你做了啥。比如写点文章，录个教程。

> 这个是免费的，感觉比那个学生版优惠更吸引人。

**Comment by TieBaMma** [comment]
我觉得这个更适合在贴吧发……当然要编辑进去也不是不可以，就放在购买方法介绍的下面呗。
