### ISSUE TITLE
反向代理包服务器 Paclet server 镜像

### ISSUE THREAD

**Issue by ryakuia** [TieBaMma/InstallTutorial#60]
> 最近看了 http://tieba.baidu.com/p/6484508125 后自己的一点想法

Paclet 是不断更新的，而且有些常用的大 Paclet 也不能镜像。可以用 CloudFlare 直接反代源服务器，每天10万次免费调用额度且不限流量，差不多够用了。速度应该不如 Gitee ，但肯定比几乎不能用的源站快。

不知道这样的设想是否可行。

PS 我找了半天没找到 Paclet 服务器源站在哪里……

> 没在 Gitee 对应项目提 issue 是因为 Gitee 看 commit log 都得注册，实在用不惯。

**Comment by asdasd1dsadsa** [comment]
源站地址是 http://pacletserver2.wolfram.com ，其中2可取1~6。六个域名都可获取相同的包资源，PacletManager会随机选取一个。PacletMirrorManager则固定选取（速度似乎较快的）2号。

**Comment by asdasd1dsadsa** [comment]
至于你说的 CloudFlare 是哪个服务，有链接吗？

**Comment by asdasd1dsadsa** [comment]
再就是顺便一提，从 PacletServer 下载数据是需要在 Header 里提供 $SystemID, $MachineID, $ActivationKey, $MachineID, $Language 的，且如果密钥无效就无法获取数据。

**Comment by asdasd1dsadsa** [comment]
改进镜像的方法我也想过一个： [新的思路：利用WolframCloud直接向github上传并导入到gitee](https://gitee.com/wolframpaclet/MirrorDevelopment/issues/I1EAQ0)

**Comment by ryakuia** [comment]
[Cloudflare 官网](cloudflare.com)

可不可以帮忙试一下可否以 https://temp-w20200801.liun.workers.dev/ 作为 Paclet server （这就是反代的包服务器网站）

**Comment by asdasd1dsadsa** [comment]
> [Cloudflare 官网](cloudflare.com)
> 
> 可不可以帮忙试一下可否以 https://temp-w20200801.liun.workers.dev/ 作为 Paclet server （这就是反代的包服务器网站）

PacletInstall 有效，速度很快。

**Comment by asdasd1dsadsa** [comment]
> [Cloudflare 官网](cloudflare.com)
> 
> 可不可以帮忙试一下可否以 https://temp-w20200801.liun.workers.dev/ 作为 Paclet server （这就是反代的包服务器网站）

PacletInstall很慢（使用的是CURLLink调用libcurl），速度在 1MB/1min 的量级，但wget手动下载很快：
```
[root@VM-0-0-centos ~]# wget --header="mathematica-systemid: Linux-x86-64" --header="mathematica-license: XXXXX-XXXX"
--header="mathematica-mathid: XXXX-XXXXX-XXXXX" --header="mathematica-language: English" --header="mathematica-activationkey: XXXX-XXXX-XXXXXX" --header="user-agent: WolframEngine/12.0.0.0 PM/3.0.0" https://temp-w20200801.liun.workers.dev/Paclets/SoundFonts1-1.0.1.paclet
--2020-08-01 20:37:50--  https://temp-w20200801.liun.workers.dev/Paclets/SoundFonts1-1.0.1.paclet
Resolving temp-w20200801.liun.workers.dev (temp-w20200801.liun.workers.dev)... 104.18.53.124, 172.67.195.21, 104.18.52.124, ...
Connecting to temp-w20200801.liun.workers.dev (temp-w20200801.liun.workers.dev)|104.18.53.124|:443... connected.
HTTP request sent, awaiting response... 200 OK
Cookie coming from temp-w20200801.liun.workers.dev attempted to set domain to wolfram.com
Length: 28229272 (27M) [application/octet-stream]
Saving to: ‘SoundFonts1-1.0.1.paclet’

SoundFonts1-1.0.1.paclet      100%[=================================================>]  26.92M  2.55MB/s    in 12s

2020-08-01 20:38:03 (2.33 MB/s) - ‘SoundFonts1-1.0.1.paclet’ saved [28229272/28229272]
```
可能libcurl的工作方式和cloudflareworker免费版支持的方式不太兼容？

**Comment by asdasd1dsadsa** [comment]
又试了一下 PacletInstall 又行了：
```
Wolfram Language 12.0.0 Engine for Linux x86 (64-bit)
Copyright 1988-2019 Wolfram Research, Inc.

In[1]:= PacletFind@"SoundFonts1"
Out[1]= {}
In[2]:= AbsoluteTiming@PacletInstall["SoundFonts1","Site"->"https://temp-w20200801.liun.workers.dev/"]
Out[2]= {18.8706, Paclet[SoundFonts1, 1.0.1, <>]}
```

**Comment by ryakuia** [comment]
> PacletInstall很慢（使用的是CURLLink调用libcurl），速度在 1MB/1min 的量级，但wget手动下载很快：

晚高峰到了，国际带宽少，自然就慢了。运气好的话还凑合，运气差就个位数kB/s

**Comment by asdasd1dsadsa** [comment]
> > PacletInstall很慢（使用的是CURLLink调用libcurl），速度在 1MB/1min 的量级，但wget手动下载很快：
> 
> 晚高峰到了，国际带宽少，自然就慢了。运气好的话还凑合，运气差就个位数kB/s

你能查日志看请求数据吗？能的话查一下目前收到了多少个对SoundFonts1和MXNetResources的请求。

**Comment by ryakuia** [comment]
> 你能查日志看请求数据吗？能的话查一下目前收到了多少个对SoundFonts1和MXNetResources的请求。

Cloudflare Workers 没有这种粒度的统计，我能看到调用次数和性能，然后就看不见了

![图片](https://user-images.githubusercontent.com/39220367/89104320-21078c80-d44b-11ea-94d7-efc523ad1c51.png)
![图片](https://user-images.githubusercontent.com/39220367/89104323-27960400-d44b-11ea-9ec6-4014da075ec2.png)

**Comment by ryakuia** [comment]
稍微改动了一下，继续求测试（

> PacletInstall很慢（使用的是CURLLink调用libcurl），速度在 1MB/1min 的量级，但wget手动下载很快：

想了想，还有个原因：第一次请求没缓存，第二次及之后请求时 Cloudflare 是使用缓存来响应，速度会快些。

**Comment by asdasd1dsadsa** [comment]
> 稍微改动了一下，继续求测试（
> 
> > PacletInstall很慢（使用的是CURLLink调用libcurl），速度在 1MB/1min 的量级，但wget手动下载很快：
> 
> 想了想，还有个原因：第一次请求没缓存，第二次及之后请求时 Cloudflare 是使用缓存来响应，速度会快些。

```
--2020-08-02 19:01:48--  https://temp-w20200801.liun.workers.dev/Paclets/SoundFonts1-1.0.1.paclet
Resolving temp-w20200801.liun.workers.dev (temp-w20200801.liun.workers.dev)... 104.18.52.124, 172.67.195.21, 104.18.53.124, ...
Connecting to temp-w20200801.liun.workers.dev (temp-w20200801.liun.workers.dev)|104.18.52.124|:443... connected.
HTTP request sent, awaiting response... 200 OK
Cookie coming from temp-w20200801.liun.workers.dev attempted to set domain to wolfram.com
Length: 28229272 (27M) [application/octet-stream]
Saving to: ‘SoundFonts1-1.0.1.paclet’

SoundFonts1-1.0.1.paclet      100%[=================================================>]  26.92M   117KB/s    in 4m 12s

2020-08-02 19:06:02 (109 KB/s) - ‘SoundFonts1-1.0.1.paclet’ saved [28229272/28229272]
```

**Comment by asdasd1dsadsa** [comment]
```
[root@VM-0-0-centos ~]# wolframscript -code '(PacletUninstall@Last@#;ToString[#,InputForm])&@AbsoluteTiming@PacletInst
all["SoundFonts1","Site"->"https://temp-w20200801.liun.workers.dev/"]'
{17.684747, Paclet["Name" -> "SoundFonts1", "Version" -> "1.0.1", "WolframVersion" -> "10.0.1+", "Extensions" -> {{"Resource", "Resources" -> {{"Accordion", "Accordion.sf2"}, {"Agogo", "Agogo.sf2"}, {"AltoSax", "AltoSax.sf2"}, {"Applause", "Applause.sf2"}, {"Atmosphere", "Atmosphere.sf2"}, {"Bagpipe", "Bagpipe.sf2"}, {"Bandoneon", "Bandoneon.sf2"}, {"Banjo", "Banjo.sf2"}, {"BaritoneSax", "BaritoneSax.sf2"}, {"BassAndLead", "BassAndLead.sf2"}, {"Bassoon", "Bassoon.sf2"}, {"Bass", "Bass.sf2"}, {"Bird", "Bird.sf2"}, {"BlownBottle", "BlownBottle.sf2"}, {"Bowed", "Bowed.sf2"}, {"BrassSection", "BrassSection.sf2"}, {"Breath", "Breath.sf2"}, {"Brightness", "Brightness.sf2"}, {"BrightPiano", "BrightPiano.sf2"}}}}, "Location" -> "/root/.WolframEngine/Paclets/Repository/SoundFonts1-1.0.1"]}
```

**Comment by asdasd1dsadsa** [comment]
```
--2020-08-02 19:13:50--  https://temp-w20200801.liun.workers.dev/Paclets/SoundFonts1-1.0.1.paclet
Resolving temp-w20200801.liun.workers.dev (temp-w20200801.liun.workers.dev)... 104.18.53.124, 172.67.195.21, 104.18.52.124, ...
Connecting to temp-w20200801.liun.workers.dev (temp-w20200801.liun.workers.dev)|104.18.53.124|:443... connected.
HTTP request sent, awaiting response... 200 OK
Cookie coming from temp-w20200801.liun.workers.dev attempted to set domain to wolfram.com
Length: 28229272 (27M) [application/octet-stream]
Saving to: ‘SoundFonts1-1.0.1.paclet’

SoundFonts1-1.0.1.paclet      100%[=================================================>]  26.92M  1.55MB/s    in 16s

2020-08-02 19:14:08 (1.68 MB/s) - ‘SoundFonts1-1.0.1.paclet’ saved [28229272/28229272]
```

**Comment by asdasd1dsadsa** [comment]
看来是缓存的原因，估计从CloudFlare那边访问WolframPacletServer也比较慢。

**Comment by ryakuia** [comment]
我看这里的介绍，似乎可以不同 Paclet 走不同安装源？Cloudflare 在国内的访问速度并不算快，如果可以这样指定的话，能不能做到 Gitee 已镜像的包走 Gitee，未镜像或有新版的包走 Cloudflare？

![图片](https://user-images.githubusercontent.com/39220367/89122812-0db4f980-d4fd-11ea-9e2d-a99bd9f51ca7.png)

PS 目前我提供的链接仅供测试，以后（如果确实需要我反代）会更换链接

**Comment by asdasd1dsadsa** [comment]
> 我看这里的介绍，似乎可以不同 Paclet 走不同安装源？Cloudflare 在国内的访问速度并不算快，如果可以这样指定的话，能不能做到 Gitee 已镜像的包走 Gitee，未镜像或有新版的包走 Cloudflare？
> 
> ![图片](https://user-images.githubusercontent.com/39220367/89122812-0db4f980-d4fd-11ea-9e2d-a99bd9f51ca7.png)
> 
> PS 目前我提供的链接仅供测试，以后（如果确实需要我反代）会更换链接

可以这样做，只需令gitee镜像站在 `PacletSites[]` 中的排名先于cloudflare的即可。

等cloudflare这边准备好了，往gitee站点的readme以及PacletMirrorClient所调取的 [mirrorlist](https://gitee.com/wolframpaclet/WolframPacletGeneral/blob/master/PacletSites.wl) 里加上地址就可以正常运作了。

**Comment by asdasd1dsadsa** [comment]
https://wolframpaclet.wolframpaclet.workers.dev
详见：https://gitee.com/wolframpaclet/WolframPacletGeneral
