### ISSUE TITLE
SharePoint 中 Mathematica_12.1.1_LINUX_CN.sh 文件信息是否有误？

### ISSUE THREAD

**Issue by qsdgy** [TieBaMma/InstallTutorial#65]
## 问题

我的结果：

名称：Mathematica_12.1.1_LINUX_CN.sh
大小：4,438,946,649
sha256: ad47b886be4a9864d70f523f792615a051d4ebc987d9a0f654b645b4eb43b30a

网页标注：
名称: Mathematica_12.1.1_LINUX_CN.sh
大小: 4485108569 字节 (4277 MiB)
SHA256: 4DD0B58581ED7DB85F3D69A2EA959BBEC258AF8C092FE9B421E1258892903E72

## 建议

希望能确认一下

**Comment by Lemmingh** [comment]
@ryaliu

**Comment by ryakuia** [comment]
最近有点忙，没处理这边的消息，抱歉。

貌似确实有问题，我是本地 7-zip 直接算出来复制的（同时复制名称 大小 SHA256三项），理论上应该不会出现这种问题，所以我也很迷。（而且我在另一个 OneDrive 传的文件大小也是`4438946649`，应该不是传炸了）

如果您下载下来能正常安装使用，麻烦告诉我一下，我去改备注。

**Comment by ryakuia** [comment]
补：应该是我的锅，官方给的大小也是`4438946649`，我迟点去改。

**Comment by ryakuia** [comment]
已更正，感谢指出问题。

**Comment by Lemmingh** [comment]
@TieBaMma
Needs tag fix:

```diff
-Area-WebPageDesign
+Area-Other
+Issue-Question
```
