### ISSUE TITLE
希望转存 12.1.1 Linux Chinese 版本

### ISSUE THREAD

**Issue by sihuan** [TieBaMma/InstallTutorial#67]
# 希望转存 12.1.1 Linux Chinese 版本
### hash:     md5 c6bcc60e55fd998e029c6985b6f3fe0c

**Comment by TieBaMma** [comment]
嗯……你的意思是不希望这个下载地址被直接编入教程吗？

**Comment by sihuan** [comment]
我前两天刚刚搭建了这个站，我不确定我能维护多长时间🙈  我怕到时候教程多了个死链
如果不介意这个倒是可以加进去🤣🤣🤣

**Comment by TieBaMma** [comment]
啊~那就先编进去了，死了再说。

**Comment by sihuan** [comment]
哈哈 好

**Comment by sihuan** [comment]
这个站已经没有再维护了，不过现在我搭建了一个使用阿里云盘的镜像网站，https://mmamirror.vercel.app/ 。现在只搬运了 Linux 12.3.1 的中文版本，后续会继续添加～
