### ISSUE TITLE
建议把下载列表顺序按版本号从高到低排列

### ISSUE THREAD

**Issue by vc12345679** [TieBaMma/InstallTutorial#7]
推荐的版本可以放在最上面，下面依次是高版本号到低版本号，觉得这样更合理一些。

**Comment by TieBaMma** [comment]
已修改。其实对于版本8旁边那句“推荐使用这个版本”我一直在犹豫是不是该去掉，毕竟已经落后三个版本了……但是最近几版Mathematica虽然新功能很多但却很不争气地一直不太稳定，让我很是犹豫。

**Comment by vc12345679** [comment]
新手用8挺好的啊，估计也没几个新手是奔着新功能来的；而且像FEM这些，按现在的实现，也没多少人会在mma上跑
