### ISSUE TITLE
所有基于mmamirror.herokuapp.com的下载链接都崩了

### ISSUE THREAD

**Issue by NanachiKyubey** [TieBaMma/InstallTutorial#71]
所以为啥要用SharePoint-API来着？

**Comment by Lemmingh** [comment]
欠费了，等下个月应该就能恢复。

**Comment by Lemmingh** [comment]
https://github.com/TieBaMma/InstallTutorial/blob/fe4023c83d8322be4bcc6a41e17e55eeaa7b05af/index.md#L89-L90

---

以百度网盘为主的镜像方案遇到许多困难，SharePoint 是替代方案之一。

#33

---

直接放 SharePoint 分享链接会难以管理，于是增加 Heroku app 这一层。

#48

**Comment by ryakuia** [comment]
1. API 可以直接显示说明文字。
2. API 获取的链接可以更方便地使用多线程下载器下载，而 SharePoint 自带的分享需要用户有一定基础才能使用非浏览器自带的下载器下载。
3. ~~具有可扩展性。~~

原因如上，跟 #48 关联不是很大。

刚开始我确实没想到下载量会这么大，现在因为个人原因不能调整，还望谅解。
