### ISSUE TITLE
百度网盘限速严重，下载速度仅有 100 kB/s

### ISSUE THREAD

**Issue by KaneGreen** [TieBaMma/InstallTutorial#9]
目前某云的封锁很严重，已经使用了IDM下载了，还是只有100K
但目前而言国内好像真的没有什么别的网盘了，iCould和OneDrive就别想了

**Comment by TieBaMma** [comment]
关于这个我也想过，是不是该返回BT……抱迅雷大腿的话搞不好还能快点……（话说最近几版好像都没看到相关的BT种子来着……）

**Comment by arcbishopw** [comment]
表示某云需要配合脚本和IDM一起使用方能愉快下载

**Comment by KaneGreen** [comment]
距离提出这个Issue已经一段时间了，试过了脚本配合IDM，成功率不高，特别是最近似乎封杀又严重了。某日看到一网站使用BaiduPanAutoReshare来提供百度云的下载高速链接，想在这里提出，然而近日突然停止维护了，但项目还在（github）。如果各位大佬有时间，可以研究一下。毕竟MMA有3~4G的文件，目前国内只有百度云能用了。

**Comment by xlucn** [comment]
可以用aria2+baiduexporter，最近一直在用，教育网的外网速度不算太高，但是能达到500kB/s的速度，不知道其他网络怎样（连接了校外联通网，依然满速大概20Mbps）。（用的话推荐使用导出Aria2下载文件的功能，deamon运行的方法我没能成功断点续传）

**Comment by KaneGreen** [comment]
### 近期百度云时常出现大文件下载，压缩包损坏的情况
（本人浏览器下载配置：Chrome+[插件](https://github.com/Kyle-Kyle/baidudl)+IDM）
本人最近已经遇到多次这种情况了，多次重复实验后，个人认为应该是以下原因：
1. 百度现在有强制限速，并不能达到宽带满速（本人100MB宽带，百度云下载700K左右）。
2. 获取的链接有有效期，据测试大约40分钟到1小时。
3. 若有效期内无法完成下载，到期后IDM下载速度变为0，需要重新获取链接，更改IDM任务属性才能继续下载。（但这几天开始似乎可以自动续了）
4. 只要下载时间长于这个有效期的，压缩包报错的几率很大。

建议：
1. 如果各位大佬有时间，可否提供上传分卷版本的压缩包？例如800MB每个分卷。
2. Mathematica_11.X.X_Chinese_WIN.zip内，文件主要分布于三个bin文件中，不建议直接上传，几个裸文件。因为压缩包能提供简单的完整性校验，而裸文件不行。
3. 如果能提供HASH校验是最好的。

最后感谢各位抽出时间阅读本回复。

#### 10.22更新：已上传分压版本

含11.2.0中文版，Windows和MacOS，来自官网申请的试用版
含有下载原始文件的校验和和各分压包的校验和
```
├─MacOS
│  ├─checksum.txt                               #外层压缩包各分包的SHA-256校验和
│  └─Mathematica_11.2.0_CHS_MAC.zip.00[1-8]     #外层压缩包的各分包
│      ├─checksum.txt                           #Mathematica_11.2.0_Chinese_MAC.dmg文件的官方提供的MD5校验和
│      └─Mathematica_11.2.0_Chinese_MAC.dmg     #官方下载的MacOS版镜像文件
└─Windows
    ├─checksum.txt                              #外层压缩包各分包的SHA-256校验和
    └─Mathematica_11.2.0_CHS_WIN.zip.00[1-7]    #外层压缩包的各分包
        ├─checksum.txt                          #Mathematica_11.2.0_Chinese_WIN.zi文件的官方提供的MD5校验和
        └─Mathematica_11.2.0_Chinese_WIN.zip    #官方下载的Windows版压缩文件
```
#### 12.2更新：因为已更新磁链下载方式，不再提供以下下载链接。
~~链接: [某度云 1eRDTugU](https://pan.baidu.com/s/1eRDTugU) 密码: `gtdv`~~

**Comment by Yinr** [comment]
要不要试试 Resilio 之类的 P2P 分享工具？

**Comment by KaneGreen** [comment]
讨论下载这个问题是没有意义的。百度云一家独大，对普通用户加以限制是必然的，而且在以后很有可能会有更强的限制和对下载工具的封锁。
截至本回复时，我在一个百度云用户的交流群体中收到普遍反映如下情况：
1. 各种下载工具都难以突破700KB/s左右
2. 在约40分钟后出现断连，需要重新获取下载地址
3. 大文件下载出错

有的用户只遇到了某一种情况，有的用户反映几种情况均有发生。
还有用户表示，在一个文件反复多次下载提示出错的情况下，他开通了百度云超级会员，然后再下载，就完全没有问题了。
所以我推测：这些极有可能是百度为了限制下载工具、提高付费率而故意为之的。
