### ISSUE TITLE
MMA 13.0.0 帮助文档的重大更新

### ISSUE THREAD

**Issue by ryakuia** [TieBaMma/InstallTutorial#93]
昨天看到文件名还没意识到这个问题，直到今天试了下软件本体

* 13.0.0 的帮助文档和主程序分离，默认不带帮助文档，通过默认浏览器拉起在线文档。
* 可以安装离线帮助文档补充包，下载前需要登录账号。
* 输入函数时的下箭头可以正常显示样例。
* 安装包大小缩减至 `~2GiB`，安装完成占用 `~5.38GiB`。

文件名变得越来越复杂，目前总结如下

|标记|意义|备注|
|---|---|---|
|`CN`|中国区下载分流版本|与软件/帮助文档语言无关|
|`BNDL`|带有完整本地帮助文档|**没下具体文件，只是猜测**<br>LINUX 只有 `BNDL`|
|`EXP`|？？？|？？？？|
|`PR3`|？？？|？？？？|
|`DLM`|下载器||
|`Chinese`|带有简体中文帮助文档|新版变化待观察|

另外，激活支持 SSO 登录账号。

**Comment by Lemmingh** [comment]
> 默认不带帮助文档，通过默认浏览器拉起在线文档

哇，虽然不是新奇操作，但我记得到 `reference.wolfram.com` 的连接不怎么稳定，这很尴尬。

**Comment by TieBaMma** [comment]
>13.0.0 的帮助文档和主程序分离，默认不带帮助文档

这个居然是默认设置？我看介绍的时候还以为会有个明确选项……
如果真是这样，那我已经能预见这会对初学者造成什么影响了…
![W0F@KKM$3LN)RESS@YM}Y5M](https://user-images.githubusercontent.com/21972695/146388913-1c4151f7-457a-40c0-837b-f72440303089.jpg)

**Comment by ryakuia** [comment]
> 这个居然是默认设置？我看介绍的时候还以为会有个明确选项……
> 如果真是这样，那我已经能预见这会对初学者造成什么影响了…

MMA本体的安装包只有 ~2GiB，帮助文档要手动安装，否则只有在线帮助文档

所以（贴吧、GH、…）教程怕不是要大改

**Comment by ryakuia** [comment]
> ![image](https://user-images.githubusercontent.com/39220367/146398951-97608623-ade8-49e3-8776-00be0c2c17ae.png)

这种甚至都不知道应该怎么改

**Comment by Lemmingh** [comment]
这恐怕已经不是“改”的问题了，是需要针对各版本区间单独写文章。

---

理想的管理方案是，固定 path，用 query 选择版本：

* <https://docs.microsoft.com/en-us/dotnet/api/system.text.rune?view=net-6.0>

但受制于 [VuePress 的静态 routing](https://v2.vuepress.vuejs.org/guide/page.html)，做不到。

另一种方法是，把版本嵌进 path：

* <https://docs.github.com/en/enterprise-cloud@latest/codespaces/the-githubdev-web-based-editor>

* <https://docs.npmjs.com/cli/v8/configuring-npm/package-json>

主要困难在于处理目录结构和背后的源文件。我不太想整出：

```text
introduction-to-mathematica.md
introduction-to-mathematica-8-10.md
introduction-to-mathematica-11-12.md
```

---

计划赶不上变化了。😱

**Comment by ryakuia** [comment]
> 理想的管理方案是，固定 path，用 query 选择版本：

像 VuePress 选择文档版本/语言那样设计呢
![image](https://user-images.githubusercontent.com/39220367/146523926-ed0241f5-fee8-4d59-9c47-5dc8c0744432.png)

这样就不只是文件名 `-11-12` 了，而是整个文件夹，甚至是多个 VuePress 编译再合并。

~~工作量⬆⬆⬆⬆⬆~~

另外这是否也意味着其他文档也向 VuePress 迁移？

> **我发现我眼瞎没看见后半截，以上内容可以忽略**
> > 另一种方法是，把版本嵌进 path：

**Comment by ryakuia** [comment]
> ```
> WLDocs_13.0.0_Chinese_MAC.pkg
> WLDocs_13.0.0_Chinese_MAC_CN.pkg
> WLDocs_13.0.0_Chinese_MAC_EXP.dmg
> WLDocs_13.0.0_Chinese_MAC_EXP_CN.dmg
> WLDocs_13.0.0_Chinese_WIN.zip
> WLDocs_13.0.0_Chinese_WIN_CN.zip
> WLDocs_13.0.0_Chinese_WIN_EXP.exe
> WLDocs_13.0.0_Chinese_WIN_EXP_CN.exe
> WLDocs_13.0.0_Japanese_MAC.pkg
> WLDocs_13.0.0_Japanese_MAC_EXP.dmg
> WLDocs_13.0.0_Japanese_WIN.zip
> WLDocs_13.0.0_Japanese_WIN_EXP.exe
> WLDocs_13.0.0_MAC.pkg
> WLDocs_13.0.0_MAC_CN.pkg
> WLDocs_13.0.0_MAC_EXP.dmg
> WLDocs_13.0.0_MAC_EXP_CN.dmg
> WLDocs_13.0.0_PR3_MAC.pkg
> WLDocs_13.0.0_PR3_MAC_EXP.dmg
> WLDocs_13.0.0_PR3_WIN.zip
> WLDocs_13.0.0_PR3_WIN_EXP.exe
> WLDocs_13.0.0_WIN.zip
> WLDocs_13.0.0_WIN_CN.zip
> WLDocs_13.0.0_WIN_EXP.exe
> WLDocs_13.0.0_WIN_EXP_CN.exe
> ```

从文件名可以推测这是 Wolfram 语言文档，但 `EXP` 是什么，`PR3` 是什么， 两者都没有的又是什么？

文件名之谜++

**Comment by ryakuia** [comment]
能不能出一个适用于新版的下载地址列表模板

现在的要素是：
|平台|安装包|文档包|
|---|---|---|
|Windows|在线文档<br>不分语言|有|
|Linux|本地文档<br>**分语言**|无|
|Mac|在线文档<br>不分语言|有|

**Comment by Lemmingh** [comment]
把 `ResourceCollection` 改成棵树？还是说……你需要有向无环图？（害怕

**Comment by aretsan** [comment]
统一用BNDL就可以了吧？就和以前没有区别了。

**Comment by ryakuia** [comment]
> 把 `ResourceCollection` 改成棵树？还是说……你需要有向无环图？（害怕

我指的是 https://github.com/TieBaMma/InstallTutorial/blob/gh-pages/docs/CONTRIBUTING.md#%E5%A6%82%E4%BD%95%E7%BC%96%E8%BE%91%E4%B8%8B%E8%BD%BD%E5%9C%B0%E5%9D%80%E5%88%97%E8%A1%A8 。


> 统一用BNDL就可以了吧？就和以前没有区别了。

没找到 Windows 和 Mac 的 `BNDL` 安装包。

**Comment by aretsan** [comment]
哦，对，看来Win和Mac用户要多几个步骤自己装文档了。

**Comment by TieBaMma** [comment]
或者先装死一段时间，赌官方不会不放Win版和Mac版的`BDNL`包。

**Comment by ryakuia** [comment]
> 或者先装死一段时间，赌官方不会不放Win版和Mac版的`BDNL`包。

从隔壁给出的文件名列表来看

> ```
> Mathematica_BNDL_13.0.0_PR3_LINUX.sh
> Mathematica_BNDL_13.0.0_PR3_MAC_EXP.dmg
> Mathematica_BNDL_13.0.0_PR3_WIN_EXP.exe
> ```

1. 带 `BNDL` 的 `MAC` `WIN` Mathematica 只有这俩；
2. 不知道 `PR3` 是什么东西；
3. 不知道 `EXP` 是什么东西；
4. 没有带 `CN` 字样的文件，说明国内没有；
5. 目前甚至不知道这几个文件有多大。

另外 13 主程序和语言包已经搬了，但实在不知道应该怎么处理。

**Comment by Lemmingh** [comment]
在 `ResourceCollection` 和 `Resource` 之间再垫一层 `ResourceBundle`，并压平 `TargetFilter` 以控制复杂度，可行吗？

```markdown
* (13.0.0) Windows + Mac
  * 主程序
    * [SharePoint](uri)
  * 本地文档 (简体中文)
    * [SharePoint](uri)
  * 本地文档 (日本語)
    * [SharePoint](uri)

* (13.0.0) Linux
  * 主程序 (含本地文档)
    * [SharePoint](uri)
```

---

猜名字……随缘试试

```
express
experiment
extra package
executable powder
exclusive property
extension provider

preview
pull request
press release
physical review
public relations
partial redistribution
```

**Comment by aretsan** [comment]
其实刚想了想，如果文档分离了那岂不是英语，中文和日语的帮助都可以装上了？

**Comment by ryakuia** [comment]
语言包的小问题还是不少的……这个 issue 关早了……

> ![image](https://user-images.githubusercontent.com/39220367/153747179-cf432ba1-19d9-4f39-9ea8-5a1138e48442.png)
>
> https://tieba.baidu.com/p/7675083708 的 1、2 楼+楼中楼

也就是说
1. MMA 依然会读取安装目录 `Documentation` 文件夹内的帮助文档。在没有匹配语言的文档时，优先展示 `Documentation` 本地文档，而不是提示查看在线文档。
2. 官方的离线帮助文档扩充包并不好用，主要问题包括
   * 语言一致才显示本地文档；
   * 有可能无法检测到本地文档；
   * 离线版无法查找帮助（没有实测）。
3. 扩充包默认安装在 `C:\Users\用户名\AppData\Local\Programs\Common\Wolfram Research\Documentation.en-us\13.0\Documentation`

---

我甚至感觉以前复制粘贴 `Documentation` 文件夹的做法更加好用

**Comment by CNMan** [comment]
> > ```
> > WLDocs_13.0.0_Chinese_MAC.pkg
> > WLDocs_13.0.0_Chinese_MAC_CN.pkg
> > WLDocs_13.0.0_Chinese_MAC_EXP.dmg
> > WLDocs_13.0.0_Chinese_MAC_EXP_CN.dmg
> > WLDocs_13.0.0_Chinese_WIN.zip
> > WLDocs_13.0.0_Chinese_WIN_CN.zip
> > WLDocs_13.0.0_Chinese_WIN_EXP.exe
> > WLDocs_13.0.0_Chinese_WIN_EXP_CN.exe
> > WLDocs_13.0.0_Japanese_MAC.pkg
> > WLDocs_13.0.0_Japanese_MAC_EXP.dmg
> > WLDocs_13.0.0_Japanese_WIN.zip
> > WLDocs_13.0.0_Japanese_WIN_EXP.exe
> > WLDocs_13.0.0_MAC.pkg
> > WLDocs_13.0.0_MAC_CN.pkg
> > WLDocs_13.0.0_MAC_EXP.dmg
> > WLDocs_13.0.0_MAC_EXP_CN.dmg
> > WLDocs_13.0.0_PR3_MAC.pkg
> > WLDocs_13.0.0_PR3_MAC_EXP.dmg
> > WLDocs_13.0.0_PR3_WIN.zip
> > WLDocs_13.0.0_PR3_WIN_EXP.exe
> > WLDocs_13.0.0_WIN.zip
> > WLDocs_13.0.0_WIN_CN.zip
> > WLDocs_13.0.0_WIN_EXP.exe
> > WLDocs_13.0.0_WIN_EXP_CN.exe
> > ```
> 
> 从文件名可以推测这是 Wolfram 语言文档，但 `EXP` 是什么，`PR3` 是什么， 两者都没有的又是什么？
> 
> 文件名之谜++

PR应该是PreRelease(预览版)，EXP不知道是什么，文件我上传一下，你们研究看看:)
[Exp.7z.gz](https://github.com/TieBaMma/InstallTutorial/files/9598076/Exp.7z.gz)

另：`CN`只能从国内CDN（无鉴权）即`*.cdsgss.com`下载，非`CN`只能从国外CDN（有鉴权）即`files.wolframcdn.com`下载

**Comment by ryakuia** [comment]
现在知道 `EXP` 约等于 Download Manager

---

发现有不少人不熟悉主程序+帮助文档的安装方法，而且 Linux 有 `BNDL` 安装包和拆分的安装包，是不是应该单独列一个下载和安装教程？

~~另外，单独打包的语言包 https://wdm.itsu.eu.org/Azusawa/WLDocsExtraction~~ 站挂了。

**Comment by asukaminato0721** [comment]
目前种子站的 query 已经半解决了。
