### ISSUE TITLE
就是好奇问下，secret.html 的作用是？

### ISSUE THREAD

**Issue by asukaminato0721** [TieBaMma/InstallTutorial#99]
偶然注意到的，尝试出域名是

https://tiebamma.github.io/InstallTutorial/secret

猜想是旧版的激活工具，但是没验证

提交记录也没写 https://github.com/TieBaMma/InstallTutorial/search?q=secret&type=commits

**Comment by TieBaMma** [comment]
确实是激活工具，某一版的 index.md 是包含了这个的。（后来这工具过时了，就让它了……）

**Comment by Lemmingh** [comment]
从 PR #2 可以看出，这是当年 [Staph. aureus](https://github.com/StephDC) 提供的 Mathematica 11.0 的算号器。
